### PR TITLE
Support single-line tags

### PR DESCRIPTION
**Pull request by rayjolt**
This pull request adds support for single-line tags. To enable testing of the single-line-tag code, it also changes the structure of the test data folder to allow multiple expected feature files, depending on what options are specified. This is quite a big change, so it is split into three different commits. If these would be easier to review as separate pull requests, please let me know. I'm also happy to rethink the test data folder structure if another approach would be better.

### CODE REVIEW

**Comment by rayjolt** [comment]
The single-line-tags implementation uses the format discussed in #22.

**Comment by rayjolt** [comment]
The Codacy check details say that the develop branch is not being analysed. I'm not sure why this is, as it was analysing it fine before. Maybe try enabling it again and see if that works?

**Comment by ducminh-phan** [comment]
> The Codacy check details say that the develop branch is not being analysed. I'm not sure why this is, as it was analysing it fine before. Maybe try enabling it again and see if that works?

I have fixed this issue. Somehow the analysis for the develop branch was turned off. I have turned it back on and it seems to work.

> This pull request adds support for single-line tags. To enable testing of the single-line-tag code, it also changes the structure of the test data folder to allow multiple expected feature files, depending on what options are specified. This is quite a big change, so it is split into three different commits. If these would be easier to review as separate pull requests, please let me know. I'm also happy to rethink the test data folder structure if another approach would be better.

It would be very helpful if you could split the commit to reorganise tests to a separate PR, so it's easier to review 😄

**Comment by rayjolt** [comment]
Closing in favour of #25 (the first two commits from this pull request squashed together).

**Pull request closed without merging**
