### PR TITLE
Add a language header to non-English feature files

### LINKED ISSUE #15: Non-English Gherkin files cause an "invalid file contents are produced" error
When I run reformat-gherkin on a Gherkin file containing the following, I get the error message "INTERNAL ERROR: Invalid file contents are produced".

```
# language: de

@tag
Funktionalität: Feature name

    Szenario: Scenario name
        Angenommen foo
        Wenn bar
        Dann baz
```

Here is the command I ran, plus the full output.

```
$ reformat-gherkin .
Error: cannot format /home/jack/projects/python/test-reformat-gherkin/test.feature: INTERNAL ERROR: Invalid file contents are produced:
Parser errors:
(2:1): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Funktionalität: Feature name'
(4:3): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Szenario: Scenario name'
(5:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Angenommen foo'
(6:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Wenn bar'
(7:5): expected: #TagLine, #FeatureLine, #Comment, #Empty, got 'Dann baz'
(8:0): unexpected end of file, expected: #TagLine, #FeatureLine, #Comment, #Empty
Please report a bug on https://github.com/ducminh-phan/reformat-gherkin/issues.
This invalid output might be helpful:
/tmp/rfmt-ghk_dk_hilnm.log

All done! 💥 💔 💥
1 file failed to reformat.

```

And here is the contents of /tmp/rfmt-ghk_dk_hilnm.log:

```
  File "/home/jack/.pyenv/versions/3.7.4/envs/test-reformat-gherkin/lib/python3.7/site-packages/reformat_gherkin/core.py", line 130, in assert_equivalent
    dst_ast = parse(dst)
  File "/home/jack/.pyenv/versions/3.7.4/envs/test-reformat-gherkin/lib/python3.7/site-packages/reformat_gherkin/parser.py", line 53, in parse
    raise InvalidInput(e) from e
@tag1
Funktionalität: Feature name

  Szenario: Scenario name
    Angenommen foo
    Wenn bar
    Dann baz
```

reformat-gherkin version: 1.0.0
Python version: 3.7.4

It looks like the problem is caused by reformat-gherkin failing to add the `# language: de` comment back to the file, which causes Gherkin to not recognise the German keywords when it tries to parse the reformatted file.

### PR DESCRIPTION
**Pull request by rayjolt**
This pull request adds language headers to non-English feature files. Fixes #15.

### CODE REVIEW

**Comment by rayjolt** [comment]
Will try and figure out the reason for these failures tomorrow.

**Comment by ducminh-phan** [comment]
@rayjolt I have fixed the issue with Codacy. Could you add a test to cover the case there is no feature in the file?

**Comment by rayjolt** [comment]
Thanks for fixing the Codacy issue. I was staring at that for quite a while trying to figure out what was wrong. :P

**Comment by ducminh-phan** [comment]
Everything seems good! Thank you for your contribution. I'm going to release v1.0.1 soon.

**Comment by rayjolt** [comment]
Thank you!

**Pull request merged**
